version: '3.8'
services:
  client:
    build: ./client
    environment:
      CHOKIDAR_USEPOLLING: "true"
    container_name: client_container
    ports: 
      - '5000:5000'
    volumes:
      - ./client:/app
      - ./app/node_modules

  server:
    build: ./server
    container_name: server_container
    ports: 
      - "5001:80"
