version: '3.8'
services:
  client:
    build: ./client
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    container_name: client_container
    ports:
      - '5002:5002'
    volumes:
      - ./client:/app
      - /app/node_modules

  db:
    image: 'mcr.microsoft.com/mssql/server'
    environment:
      SA_PASSWORD: 'Your_password123'
      ACCEPT_EULA: 'Y'

  server:
    container_name: server_container
    build: ./server/src/
    ports:
      - '5000:5000'
    depends_on:
      - db
