version: '3.8'
services:
  client:
    build: ./client
    environment:
      CHOKIDAR_USEPOLLING: "true"
    container_name: client_container
    ports: 
      - '5000:5000'
    volumes:
      - ./client:/app
      - /app/node_modules

  server:
    image: mcr.microsoft.com/dotnet/sdk:6.0-alpine
    container_name: server_container
    environment: 
        - ASPNETCORE_URLS=http://+:80
        - DOTNET_USE_POLLING_FILE_WATCHER=1
    volumes:
        - ./server:/app
    ports:
        - 5001:80
    working_dir: /app
    command: dotnet watch run --no-launch-profile

